### ISSUE TITLE
Performance improvement for large number of regex

### ISSUE THREAD

**Issue by morwen** [bd82/regexp-to-ast#17] opened 2019-03-09 14:54 UTC
At the moment [isQuantifier](https://github.com/bd82/regexp-to-ast/blob/563924ba8c0492499a4c0cb4d39bf08490868fda/lib/regexp-to-ast.js#L690) function checks if an exception was thrown by [quantifier ](https://github.com/bd82/regexp-to-ast/blob/563924ba8c0492499a4c0cb4d39bf08490868fda/lib/regexp-to-ast.js#L155) function.

This leads to performance degradation when a large number of regex are used. A better approach would be to check for return value of quantifier function.

On our code base with 1000 tokens ASSERT_EXISTS in quantifier function takes up around 750ms (on high end hardware).

**Comment by bd82** [comment] 2019-03-09 16:34
I would be willing to accept a PR that improve this.

But are you sure the performance impact is due to the try/catch block?
Newer version of V8 should no longer have issues optimizing functions with try/catch blocks.
It seems more likely to me that the problem is because isQuantifier seems to do **backtracking**
and therefor the input could be parsed multiple times.

**Comment by morwen** [comment] 2019-03-09 16:57
We are running electron application, so unfortunately it's not the latest Chrome version.
I just modified isQuantifier/quantifier to compare performance difference and it looks like this: 

before:
![image](https://user-images.githubusercontent.com/2011923/54074555-1071d780-4294-11e9-971c-182f132a1299.png)

after:
![image](https://user-images.githubusercontent.com/2011923/54074559-1962a900-4294-11e9-9721-3a7cf7644c56.png)

I was thinking to modify quantifier function to something like this:
```js
            if (skipVerify === true && range === undefined) {
                return range;
            }
            
            ASSERT_EXISTS(range)
```
unless you have a better suggestion.

I forgot to include versions in the original bug report.
Electron: 4.0.4
Node.js: 10.11.0
Chrome: 69.0.3497.106
V8: 6.9.427.24-electron.0
OS: Windows_NT win32 10.0.17763

**Comment by bd82** [comment] 2019-03-09 18:07
This bit could be optimized:
https://github.com/bd82/regexp-to-ast/blob/563924ba8c0492499a4c0cb4d39bf08490868fda/lib/regexp-to-ast.js#L242-L244

Because ***isQuantifier*** actually returns the quantifier if it is a quantifier and than the quantifier is parsed **again**... so that is ineffective...

It also looks like ASSERT_EXISTS may be called sometimes redundantly in ***quantifier***
https://github.com/bd82/regexp-to-ast/blob/563924ba8c0492499a4c0cb4d39bf08490868fda/lib/regexp-to-ast.js#L206

I think that TurboFan should be in V8 for a long time now (years?) so I doubt your 6-9 months old electron is the problem.

**Comment by bd82** [comment] 2019-03-09 18:12
The first step would be to create a a performance benchmark.
Generate/Copy a large number of regExp literals and see how long it takes to parse those.

Only then can we properly explore how changes in the source code affect performance.

Here is a simple benchmark from another package I've created
- https://github.com/bd82/toml-tools/blob/master/packages/parser/benchmark/benchmark.js
It can be used as a template for a benchmark.

**Comment by bd82** [comment] 2019-03-09 18:13
Btw @morwen what scenario are these 1,000 tokens used?
In Chevrotain?

**Comment by morwen** [comment] 2019-03-09 19:23
Thanks for feedback!
Yes, we are using chevrotain to create an Elasticsearch grammar. 
I'll look into creating a benchmark and PR.

**Comment by bd82** [comment] 2019-03-09 19:29
>  Yes, we are using chevrotain to create an Elasticsearch grammar.

Are you initializing your lexer many times? While something like 750ms is definitively excessive on a high end machine, it should only be paid once.

There may be optimization's on Chevrotain's side that need be implemented here:
https://github.com/SAP/chevrotain/issues/907

**Comment by morwen** [comment] 2019-03-09 19:31
We are initializing lexer once in a worker thread (to avoid blocking UI).

**Comment by bd82** [comment] 2019-03-09 19:33
> We are initializing lexer once in a worker thread (to avoid blocking UI).

o.k as long as its once total per user.

**Comment by bd82** [comment] 2019-04-01 21:54
closing as this was merged and released

**Closed by bd82** 2019-04-01 21:54 UTC
